name: Fine-tune ChatGPT

on:
  push:
    branches:
      - master

jobs:
  fine-tune:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set environment variable
      run: echo "MY_ENV_VAR=${{ secrets.MY_SECRET }}" >> $GITHUB_ENV

    - name: Install Python
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip

    - name: Install OpenAI package and other dependent packages
      run: |
        pip3 install openai
        pip install pandas


    - name: Run fine-tune script
      run: python3 scripts/fine_tune.py

    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        git add fine_tuned_data.txt
        git commit -m "Update fine-tuned data"
        git push origin master

